# Generated by Django 5.2.3 on 2025-07-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicamento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='droga',
            field=models.CharField(max_length=100),
        ),
    ]
